const clubsList = [        
        "AC Milan",
        "AZ",
        "Aberdeen",
        "Ajax",
        "Alaves",
        "Alkmaar",
        "Almeria",
        "Angers",
        "Argentina",
        "Arouca",
        "Arsenal",
        "Aston Villa",
        "Atalanta",
        "Athletic Bilbao",
        "Atletico Madrid",
        "Auxerre",
        "Azores",
        "Barcelona",
        "Belgium",
        "Benfica",
        "Birmingham",
        "Blackburn",
        "Boavista",
        "Bologna",
        "Bolton",
        "Bournemouth",
        "Braga",
        "Breda",
        "Brentford",
        "Brest",
        "Brighton",
        "Bristol",
        "Burnley",
        "Cadiz",
        "Cagliari",
        "Cardiff",
        "Casa P",
        "Celta Vigo",
        "Celtic",
        "Charlton",
        "Chaves",
        "Chelsea",
        "Clermont-Ferrand",
        "Como",
        "Cornella",
        "Coventry",
        "Cremonese",
        "Crystal Palace",
        "Derby",
        "Dundee",
        "Dundee U",
        "E Amadora",
        "Eibar",
        "Elche",
        "Empoli",
        "Espanyol",
        "Estoril",
        "Everton",
        "Falkirk",
        "Famalicao",
        "Farense",
        "Feyenoord",
        "Feyernoord",
        "Fiorentina",
        "Frosinone",
        "Fulham",
        "GA Eagles",
        "Genoa",
        "Getafe",
        "Girona",
        "Glasgow R",
        "Granada",
        "Guimaraes",
        "Hearts",
        "Heerenveen",
        "Hellas Verona",
        "Heracles Almelo",
        "Hibernian",
        "Huddersfield",
        "Hull",
        "Inter Milan",
        "Ipswich",
        "Juventus",
        "Kilmarnock",
        "Las Palmas",
        "Lazio",
        "Le Havre",
        "Lecce",
        "Leeds",
        "Leganes",
        "Leicester",
        "Leicester City",
        "Lens",
        "Levante",
        "Lille",
        "Liverpool",
        "Livingston",
        "Lorient",
        "Luton",
        "Lyon",
        "Mallorca",
        "Man City",
        "Man United",
        "Marseille",
        "Metz",
        "Middlesbrough",
        "Millwall",
        "Monaco",
        "Montpellier",
        "Monza",
        "Moreirense",
        "Motherwell",
        "Nantes",
        "Napoli",
        "Newcastle",
        "Nice",
        "Nijmegen",
        "Norwich",
        "Nottingham",
        "Osasuna",
        "Oviedo",
        "Oxford",
        "PSV",
        "Paris FC",
        "Paris SG",
        "Parma",
        "Pisa",
        "Plymouth",
        "Porto",
        "Portsmouth",
        "Preston",
        "Queens Park R",
        "Rangers",
        "Real Betis",
        "Real Madrid",
        "Real Sociedad",
        "Reims",
        "Rennes",
        "Rio Ave",
        "Roma",
        "Ross C",
        "Rotherham",
        "Rotterdam",
        "S Johnstone",
        "S Lisbon",
        "S Mirren",
        "Saint-Etienne",
        "Salernitana",
        "Salzbrug",
        "Sampdoria",
        "Santa Clara",
        "Sassuolo",
        "Sevilla",
        "Sheffield United",
        "Sheffield W",
        "Sittard",
        "Southampton",
        "Spezia",
        "Sporting CP",
        "Stoke",
        "Strasbourg",
        "Sunderland",
        "Swansea",
        "Torino",
        "Tottenham",
        "Toulouse",
        "Twente",
        "Udinese",
        "Unlicensed",
        "Utrecht",
        "V Arnhem",
        "Valencia",
        "Valladolid",
        "Vallecano",
        "Venezia",
        "Verona",
        "Villareal",
        "Vitoria",
        "Vizela",
        "Waalwijk",
        "Watford",
        "West Bromwich",
        "West Ham",
        "Wigan",
        "Willem",
        "Wolves",
        "Zwolle"
    ];

Ext.define('DLSStats.store.ClubsStore', {
    extend: 'Ext.data.Store',
    alias: 'store.clubsstore',

    fields: ['name'],
    data: clubsList.map(function (name) {
        return { name: name };
    })
});
