const nationsList = [
        "Albania",
        "Algeria",
        "Andorra",
        "Angola",
        "Antigua & Barbuda",
        "Argentina",
        "Armenia",
        "Australia",
        "Austria",
        "Belarus",
        "Belgium",
        "Benin",
        "Bermuda",
        "Bosnia & Herzegovina",
        "Brazil",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Cameroon",
        "Canada",
        "Cape Verde",
        "Central Africa",
        "Chile",
        "Colombia",
        "Comoros",
        "Congo",
        "Costa Rica",
        "Croatia",
        "Cuba",
        "Curacao",
        "Cyprus",
        "Czech Republic",
        "DR Congo",
        "Denmark",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "Egypt",
        "England",
        "Equatorial Guinea",
        "Estonia",
        "Finland",
        "France",
        "Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Greece",
        "Grenada",
        "Guadeloupe",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Honduras",
        "Hungary",
        "Iceland",
        "Indonesia",
        "Irag",
        "Iran",
        "Ireland",
        "Israel",
        "Italy",
        "Ivory Coast",
        "Jamaica",
        "Japan",
        "Jordan",
        "Kenya",
        "Kosovo",
        "Latvia",
        "Liberia",
        "Libya",
        "Lithuania",
        "Luxembourg",
        "Lybia",
        "Madagascar",
        "Mali",
        "Malta",
        "Mexico",
        "Moldova",
        "Montenegro",
        "Morocco",
        "Mozambique",
        "Namibia",
        "Netherlands",
        "New Zealand",
        "Niger",
        "Nigeria",
        "North Macedonia",
        "North. Ireland",
        "Norway",
        "Panama",
        "Paraguay",
        "Peru",
        "Philippines",
        "Poland",
        "Portugal",
        "Puerto Rico",
        "Romania",
        "Russia",
        "Saudi Arabia",
        "Scotland",
        "Senegal",
        "Serbia",
        "Sierra Leone",
        "Slovakia",
        "Slovenia",
        "South Africa",
        "South Korea",
        "Spain",
        "St. Kitts & Nevis",
        "St. Lucia",
        "Suriname",
        "Sweden",
        "Switzerland",
        "Syria",
        "Tanzania",
        "Togo",
        "Trinidad & Tobago",
        "Tunisia",
        "Turkey",
        "UAE",
        "USA",
        "Uganda",
        "Ukraine",
        "Uruguay",
        "Uzbekistan",
        "Venezuela",
        "Wales",
        "Wolves",
        "Zambia",
        "Zimbabwe"
    ]

Ext.define('DLSStats.store.NationsStore', {
    extend: 'Ext.data.Store',
    alias: 'store.nationsstore',

    fields: ['name'],
    data: nationsList.map(function (name) {
        return { name: name };
    })
});
